fix(Activity Tracker): Added support for event streams targets in Atracker v2 API
IBM/platform-services-go-sdk pull request #206
Opened 2022-09-14 21:36 UTC by veenanr

## PR summary

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

## Other information

2022-09-14 21:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/IBM/platform-services-go-sdk?pullRequest=206) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/IBM/platform-services-go-sdk?pullRequest=206) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/IBM/platform-services-go-sdk?pullRequest=206) it.</sub>

2022-09-14 21:54 UTC, padamstx requested changes
I noticed a few changes needed in the integration tests to allow the tests to exercise all three target types independently.

2022-09-14 21:54 UTC, padamstx commented on atrackerv2/atracker_v2_integration_test.go
> +			targetIDLink2 = *target.ID
Probably shouldn't share the link variable with the testcase above.
```suggestion
			targetIDLink3 = *target.ID
```

2022-09-14 21:54 UTC, padamstx commented on atrackerv2/atracker_v2_integration_test.go
> +				ID:             &targetIDLink2,
```suggestion
				ID:             &targetIDLink3,
```

2022-09-14 21:54 UTC, padamstx commented on atrackerv2/atracker_v2_integration_test.go
> +				ID:             &targetIDLink2,
Note that the cleanup code should also include a section to delete the target whose id is targetIDLink3

2022-09-15 15:23 UTC, padamstx approved these changes
LGTM

Could you please post a screenshot of a successful run of the atrackerv2 integration tests and examples for atrackerv2?
(e.g. `cd atrackerv2`, `go test -tags=integration,examples`)?  Thanks!

Once we have those results, I'll go ahead and merge.

2022-09-15 15:25 UTC, veenanr commented
![image](https://user-images.githubusercontent.com/47424177/190443966-53294443-ec01-4d21-87b1-1ab605584db0.png)

2022-09-15 15:32 UTC, padamstx commented
In the screen shot, it looks like you ran only unit and integration tests but not examples.  You can use `-tags=integration,examples` to run unit tests, int tests and examples all at once.

2022-09-15 16:05 UTC, veenanr commented
[testRun.txt](https://github.com/IBM/platform-services-go-sdk/files/9577003/testRun.txt)

2022-09-15 16:09 UTC, merged

2022-09-15 16:13 UTC, ibm-devx-sdk commented
:tada: This PR is included in version 0.28.3 :tada:

The release is available on [GitHub release](https://github.com/IBM/platform-services-go-sdk/releases/tag/v0.28.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: