add list rule with service_group_id test
IBM/platform-services-go-sdk pull request #208
Opened 2022-10-03 17:25 UTC by cam-d12

## PR summary

This PR adds CBR support for the new service_group_id parameter in rules. 

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  

No current behavior should be modified. Adds the further control to be able to apply rules to service groups

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

## Other information

2022-10-12 14:13 UTC, soohoowoohoo reviewed
Looks good.

2022-10-12 14:17 UTC, soohoowoohoo requested changes
A few comments.

2022-10-12 14:18 UTC, soohoowoohoo commented on contextbasedrestrictionsv1/context_based_restrictions_v1_integration_test.go
> +			Expect(response.StatusCode).To(Equal(201))
Should be a 200

2022-10-13 02:40 UTC, soohoowoohoo reviewed
LGTM

2022-10-14 17:23 UTC, padamstx approved these changes
LGTM

2022-10-14 17:25 UTC, merged

2022-10-14 17:30 UTC, ibm-devx-sdk commented
:tada: This PR is included in version 0.28.6 :tada:

The release is available on [GitHub release](https://github.com/IBM/platform-services-go-sdk/releases/tag/v0.28.6)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: