feat (IAM Access Groups): Add support for access group templates
IBM/platform-services-go-sdk pull request #266
Opened 2023-07-22 20:34 UTC by hariarla

## PR summary

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [ ] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  

SDK adopters will be able to call access group template and assignment APIs.
## Does this PR introduce a breaking change?    
- [ ] Yes
- [ ] No

## Other information

API Definition
[Stage](https://test.cloud.ibm.com/docs/access-groups)
[Production](https://cloud.ibm.com/docs/access-groups)

**Tests**:
<img width="1259" alt="Screenshot 2023-07-23 at 1 44 27 AM" src="https://github.com/IBM/platform-services-go-sdk/assets/68221277/0096bb7b-2dee-46e0-abc7-8d081a9e4351">
**Example Tests**:
<img width="1259" alt="Screenshot 2023-07-23 at 1 50 53 AM" src="https://github.com/IBM/platform-services-go-sdk/assets/68221277/37033791-6dfe-4872-ada3-0eab3d4ff699">
**Integration Tests**:
<img width="1259" alt="Screenshot 2023-07-23 at 1 56 48 AM" src="https://github.com/IBM/platform-services-go-sdk/assets/68221277/d35fc29a-de05-45cf-a772-fd5a37068d53">

2023-07-27 16:28 UTC, pyrooka requested changes
Please fix the issues I mentioned!
To fix the builds you have to re-add the test imports and to fix the style issues you should run `go fmt iamaccessgroupsv2/*.go`. That will probably solve most of the code style related problems.

2023-07-27 16:28 UTC, pyrooka commented on iamaccessgroupsv2/iam_access_groups_v2_examples_test.go
> -//go:build examples
This should not be removed. Since Go.1.17 this is the preferred syntax.

2023-07-27 16:28 UTC, pyrooka commented on iamaccessgroupsv2/iam_access_groups_v2_examples_test.go
> -	. "github.com/onsi/gomega"
Why these have been removed? As you can see the builds failed due these missing dependencies.

2023-07-27 16:28 UTC, pyrooka commented on iamaccessgroupsv2/iam_access_groups_v2_examples_test.go
> +		testAssignmentEtag	string
Please format the code to follow the style above: the variable types on each line is in the same column.
`go fmt iamaccessgroupsv2/*.go`

2023-07-27 16:28 UTC, pyrooka commented on iamaccessgroupsv2/iam_access_groups_v2_examples_test.go
> +			// end-create_template
Please add a new line before the `// end-...` tag.
```suggestion

			// end-create_template
```

2023-07-27 16:28 UTC, pyrooka commented on iamaccessgroupsv2/iam_access_groups_v2_examples_test.go
> +			// begin-list_templates
Please add a new line after the `// begin-...` tag.
```suggestion
			// begin-list_templates

```

2023-07-27 16:28 UTC, pyrooka commented on iamaccessgroupsv2/iam_access_groups_v2_examples_test.go
> +			// end-list_template_versions
Please add a new line before the // end-... tag.
```suggestion

			// end-list_template_versions
```

2023-07-27 16:28 UTC, pyrooka commented on iamaccessgroupsv2/iam_access_groups_v2_examples_test.go
> +			// begin-list_template_versions
Please add a new line after the // begin-... tag.
```suggestion
			// begin-list_template_versions

```

2023-07-27 16:28 UTC, pyrooka commented on iamaccessgroupsv2/iam_access_groups_v2_examples_test.go
> +			// end-list_templates
Please add a new line before the // end-... tag.
```suggestion

			// end-list_templates
```

2023-07-27 16:28 UTC, pyrooka commented on iamaccessgroupsv2/iam_access_groups_v2_integration_test.go
> -	. "github.com/onsi/gomega"
Why?

2023-07-27 16:28 UTC, pyrooka commented on iamaccessgroupsv2/iam_access_groups_v2_integration_test.go
> +		testAssignmentEtag	string
Please re-format this to follow the previous style (types on the same column).
`go fmt iamaccessgroupsv2/*.go`

2023-07-27 16:28 UTC, pyrooka commented on iamaccessgroupsv2/iam_access_groups_v2_integration_test.go
> +
```suggestion
```

2023-07-27 16:28 UTC, pyrooka commented on iamaccessgroupsv2/iam_access_groups_v2_integration_test.go
> -//go:build integration
This shoud not be removed.

2023-08-04 15:22 UTC, hariarla commented
Basic Tests:
<img width="868" alt="Screenshot 2023-08-04 at 7 32 53 PM" src="https://github.com/IBM/platform-services-go-sdk/assets/68221277/fa07d83e-d982-4ea3-86b6-c3387df2615a">
<img width="868" alt="Screenshot 2023-08-04 at 7 33 35 PM" src="https://github.com/IBM/platform-services-go-sdk/assets/68221277/7dfd3c52-0d2e-4214-b8be-9fb54695e3b0">

Integration Tests:
<img width="868" alt="Screenshot 2023-08-04 at 8 18 20 PM" src="https://github.com/IBM/platform-services-go-sdk/assets/68221277/c2ff8d4b-03bf-4209-b129-2393d0c523f4">
 Example Tests:
<img width="963" alt="Screenshot 2023-08-04 at 8 36 32 PM" src="https://github.com/IBM/platform-services-go-sdk/assets/68221277/f34ff744-be27-4f0c-a6e0-2b09e0172174">

2023-08-07 18:39 UTC, padamstx approved these changes
LGTM

2023-08-11 13:40 UTC, hariarla commented
Unit Tests:
<img width="712" alt="Screenshot 2023-08-11 at 2 31 09 PM" src="https://github.com/IBM/platform-services-go-sdk/assets/68221277/95cd283b-2392-4d26-9ac7-0310f5335013">

Integration Tests:
<img width="712" alt="Screenshot 2023-08-11 at 2 31 33 PM" src="https://github.com/IBM/platform-services-go-sdk/assets/68221277/096e361e-d475-4579-a98a-18c1552ed94c">

Example Tests:
<img width="712" alt="Screenshot 2023-08-11 at 7 08 30 PM" src="https://github.com/IBM/platform-services-go-sdk/assets/68221277/ec7374c8-b672-439c-8c18-40b6a132cbde">

2023-08-11 14:30 UTC, merged