fix (ATracker: regen-atracker-04012024 Add Cloud Logs target type sup…
IBM/platform-services-go-sdk pull request #314
Opened 2024-04-01 20:51 UTC by veenanr

…port

## PR summary
Add support for a new ATracker target type (cloud-logs) and its endpoint fields

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  
ATracker will support a new target type (cloud-logs) in addition to the existing target types

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

## Other information
Unit tests results:

```
veenarao$ go test
go: downloading github.com/onsi/gomega v1.31.1
Running Suite: AtrackerV2 Suite
===============================
Random Seed: 1712004023
Will run 94 of 94 specs

••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
Ran 94 of 94 Specs in 4.006 seconds
SUCCESS! -- 94 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
ok  	github.com/IBM/platform-services-go-sdk/atrackerv2	5.064s

```

Integration test results:

```
veenarao$ go test github.com/IBM/platform-services-go-sdk/atrackerv2 -tags="integration" -v
=== RUN   TestAtrackerV2
Running Suite: AtrackerV2 Suite
===============================
Random Seed: 1712004111
Will run 137 of 137 specs

••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
------------------------------
• [SLOW TEST:7.479 seconds]
AtrackerV2 Integration Tests
/Users/veenarao/go/src/github.com/IBM/platform-services-go-sdk/atrackerv2/atracker_v2_integration_test.go:42
  DeleteTarget - Delete a target
  /Users/veenarao/go/src/github.com/IBM/platform-services-go-sdk/atrackerv2/atracker_v2_integration_test.go:756
    DeleteTarget(deleteTargetOptions *DeleteTargetOptions)
    /Users/veenarao/go/src/github.com/IBM/platform-services-go-sdk/atrackerv2/atracker_v2_integration_test.go:804
------------------------------

Ran 137 of 137 Specs in 16.669 seconds
SUCCESS! -- 137 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestAtrackerV2 (16.71s)
PASS
ok  	github.com/IBM/platform-services-go-sdk/atrackerv2	17.733s
```

2024-04-01 22:38 UTC, padamstx requested changes
Everything looks good, except the copyright year in a couple files.  Could you fix that please?

2024-04-01 22:38 UTC, padamstx commented on atrackerv2/atracker_v2_integration_test.go
> + * (C) Copyright IBM Corp. 2022.
```suggestion
 * (C) Copyright IBM Corp. 2024.
```

2024-04-01 22:38 UTC, padamstx commented on atrackerv2/atracker_v2_examples_test.go
> + * (C) Copyright IBM Corp. 2022.
```suggestion
 * (C) Copyright IBM Corp. 2024.
```

2024-04-02 00:19 UTC, veenanr commented on atrackerv2/atracker_v2_integration_test.go
> + * (C) Copyright IBM Corp. 2022.
Updated

2024-04-02 00:20 UTC, veenanr commented on atrackerv2/atracker_v2_examples_test.go
> + * (C) Copyright IBM Corp. 2022.
Updated

2024-04-02 13:53 UTC, padamstx approved these changes
LGTM

2024-04-02 13:53 UTC, merged