feat(Catalog Management): support change notices and plan id in offer…
IBM/platform-services-go-sdk pull request #325
Opened 2024-05-01 14:24 UTC by benbuchanan

…ing instance create

## PR summary

Need these changes to update the catalog management terraform provider.
- Now support plan id on offering instance create
- New field called change notices on an offering version

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  

Just adding new fields that our api now supports.  Needed to update our terraform provider.

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

## Other information

2024-05-01 14:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/IBM/platform-services-go-sdk?pullRequest=325) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/IBM/platform-services-go-sdk?pullRequest=325) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/IBM/platform-services-go-sdk?pullRequest=325) it.</sub>

2024-05-01 18:47 UTC, padamstx requested changes
1. Need to re-gen with the latest version of the SDK generator in order to leverage the new support for error handling in the Go SDK and Terraform providers.
2. Need to add working examples code and integration tests for the GetPlan, DeletePlan, ConsumablePlan, and SetDeprecatePlan operations.

2024-05-01 18:47 UTC, padamstx commented on catalogmanagementv1/catalog_management_v1_examples_test.go
> +		It(`GetOfferingChangeNotices request example`, func() {
There are no examples for the get_plan, delete_plan, consumable_plan or set_deprecate_plan operations.

2024-05-01 18:47 UTC, padamstx commented on catalogmanagementv1/catalog_management_v1_integration_test.go
>  				Evaluations: []catalogmanagementv1.Evaluation{*evaluationModel},
No integration tests for the get_plan, delete_plan, consumable_plan, set_deprecate_plan operations.

2024-05-01 19:39 UTC, benbuchanan commented
@padamstx Our API does not have the ability to create a plan unless the token making the call is an approver (Plans are created in Partner Center and they call us with an approver token to create them).  We just provide another way to manage them with the delete, deprecate, publish.

Is there precedence for running tests with a different token?

2024-05-02 19:50 UTC, benbuchanan commented
example tests:
```
Ran 709 of 738 Specs in 48.630 seconds
SUCCESS! -- 709 Passed | 0 Failed | 0 Pending | 29 Skipped
PASS
ok  	github.com/IBM/platform-services-go-sdk/catalogmanagementv1	49.332s
```

integration tests:
```
Ran 720 of 776 Specs in 43.556 seconds
SUCCESS! -- 720 Passed | 0 Failed | 0 Pending | 56 Skipped
PASS
ok  	github.com/IBM/platform-services-go-sdk/catalogmanagementv1	44.380s
```

2024-05-03 17:59 UTC, padamstx approved these changes
LGTM

2024-05-03 18:00 UTC, merged

2024-05-03 18:24 UTC, ibm-devx-sdk commented
:tada: This PR is included in version 0.62.11 :tada:

The release is available on [GitHub release](https://github.com/IBM/platform-services-go-sdk/releases/tag/v0.62.11)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: