feat(Catalog Management): regen after recent api changes
IBM/platform-services-go-sdk pull request #328
Opened 2024-05-21 16:02 UTC by benbuchanan

## PR summary

regenerating after recent api changes

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  

adding new endpoints, removing some deprecated fields

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

## Other information

2024-05-21 16:36 UTC, benbuchanan commented
```
integration
Ran 735 of 791 Specs in 45.839 seconds
SUCCESS! -- 735 Passed | 0 Failed | 0 Pending | 56 Skipped
PASS
ok  	github.com/IBM/platform-services-go-sdk/catalogmanagementv1	46.832s

example
Ran 723 of 753 Specs in 45.915 seconds
SUCCESS! -- 723 Passed | 0 Failed | 0 Pending | 30 Skipped
PASS
ok  	github.com/IBM/platform-services-go-sdk/catalogmanagementv1	46.958s
```

2024-05-21 16:45 UTC, padamstx commented on catalogmanagementv1/catalog_management_v1_examples_test.go
> +			// begin-get_offering
this should be 
```suggestion
			// begin-get_offering_stats
```

2024-05-21 16:46 UTC, padamstx requested changes
I approved too quickly before :)
The examples code needs a couple of small changes.

2024-05-21 17:05 UTC, padamstx requested changes

2024-05-21 17:05 UTC, padamstx commented on catalogmanagementv1/catalog_management_v1_examples_test.go
> +			// end-get_offering-stats
```suggestion
			// end-get_offering_stats
```

2024-05-22 17:06 UTC, padamstx approved these changes
LGTM

2024-05-22 17:09 UTC, merged

2024-05-22 17:16 UTC, ibm-devx-sdk commented
:tada: This PR is included in version 0.63.0 :tada:

The release is available on [GitHub release](https://github.com/IBM/platform-services-go-sdk/releases/tag/v0.63.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: