feat(IAM Identity): adding effective account settings
IBM/platform-services-go-sdk pull request #347
Opened 2024-08-01 12:12 UTC by pooraniss-ibm

## PR summary
new endpoint to get Effective account settings, 
also has action control added to existing template calls. 

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [ ] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  

## Does this PR introduce a breaking change?    
- [ ] Yes
- [ ] No

## Other information

2024-08-01 12:13 UTC, pooraniss-ibm commented
<img width="1170" alt="Screenshot 2024-07-31 at 19 54 31" src="https://github.com/user-attachments/assets/e1025455-b47a-4060-b84b-a7e278365b50">
<img width="821" alt="Screenshot 2024-08-01 at 09 40 02" src="https://github.com/user-attachments/assets/b755b3bf-a0cf-4a73-bebb-558abac8354f">

2024-08-01 12:14 UTC, pooraniss-ibm commented
added screenshots of passing test cases :)

2024-08-02 21:43 UTC, padamstx commented
@pooraniss-ibm Could you please sign off on your commit?  That is the "DCO" failure in the list of checks for the PR.  To sign off on your commit, you could use the "-s" option on `git commit`.  More details here: https://github.com/IBM/platform-services-go-sdk/blob/main/update_service.md#7-open-pr-with-your-changes

2024-08-02 21:47 UTC, padamstx requested changes
Need to regen with the latest generator and production API defn.

2024-08-02 21:47 UTC, padamstx commented on iamidentityv1/iam_identity_v1.go
> +const DefaultServiceURL = "https://iam.test.cloud.ibm.com"
You generated the code using the staging version of the API definition again, didn't you? :joy:
You'll need to re-gen the code using the production version of the API definition

2024-08-02 21:47 UTC, padamstx commented on iamidentityv1/iam_identity_v1.go
> +const DefaultServiceURL = "https://iam.test.cloud.ibm.com"
Also, please upgrade to the very latest version of the SDK generator before you re-gen the code using the production API defn.

2024-08-12 21:08 UTC, padamstx approved these changes
LGTM

2024-08-12 21:33 UTC, merged

2024-08-12 21:40 UTC, ibm-devx-sdk commented
:tada: This PR is included in version 0.66.0 :tada:

The release is available on [GitHub release](https://github.com/IBM/platform-services-go-sdk/releases/tag/v0.66.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: