feat(partner center sell): add custom service parameters and other gc…
IBM/platform-services-go-sdk pull request #366
Opened 2024-12-18 15:54 UTC by HarasztiaPeter

… metadata service flags

## PR summary

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [ ] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  

## Does this PR introduce a breaking change?    
- [ ] Yes
- [ ] No

## Other information

2025-01-03 08:29 UTC, HarasztiaPeter commented
![Uploading Screenshot 2025-01-03 at 09.28.15.png…]()

2025-01-03 08:30 UTC, HarasztiaPeter commented
<img width="1719" alt="Screenshot 2025-01-03 at 09 28 15" src="https://github.com/user-attachments/assets/0ef3dfc5-ef60-4fed-b7a7-7664e2d812a7" />

2025-01-03 08:31 UTC, HarasztiaPeter commented
I ll be out of office, @balazs-marjan  will take over please grant him all the needed access to edit this PR, he is already a contributor to the repo.

2025-01-06 19:02 UTC, padamstx requested changes
PR looks good overall, but we just need to back out the changes to go.mod

2025-01-07 22:50 UTC, padamstx commented
In order to solve the Travis-CI build problems, we have enabled GH actions in this project.  I've rebased this feature branch on top of our updated main branch which has the GH actions-related changes.

2025-01-07 22:50 UTC, merged

2025-01-07 22:54 UTC, ibm-devx-sdk commented
:tada: This PR is included in version 0.73.0 :tada:

The release is available on [GitHub release](https://github.com/IBM/platform-services-go-sdk/releases/tag/v0.73.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: