fix: add labels to examples
IBM/platform-services-go-sdk pull request #97
Opened 2021-03-23 14:34 UTC by Andras-Csanyi

## PR summary
This PR adds labels to example output, so that it is easier to identify which section of the output belongs to which method.

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [ ] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Current vs new behavior  

## Does this PR introduce a breaking change?    
- [ ] Yes
- [ ] No

## Other information

2021-03-23 16:45 UTC, pyrooka requested changes
Apart from the requested changes looks good. What do you think about the things I've mentioned?

2021-03-23 16:45 UTC, pyrooka commented on casemanagementv1/case_management_v1_examples_test.go
> -	. "github.com/onsi/gomega"
These imports are necessary. Without them cannot run the tests (Describe, Expect, It, etc...)

2021-03-23 16:45 UTC, pyrooka commented on casemanagementv1/case_management_v1_examples_test.go
> +			fmt.Printf("\nRemoveWatchlist() result:\n &s \n", string(b))
Typo.
```suggestion
			fmt.Printf("\nRemoveWatchlist() result:\n %s \n", string(b))
```

2021-03-23 16:45 UTC, pyrooka commented on atrackerv1/atracker_v1_examples_test.go
> +			fmt.Printf("\nCreateTarget() result:\n %s \n", string(b))
Using space around the `%s` causes "not that pretty" indentation:
```
UploadFile() result:
 {
  "id": "xxx",
  "filename": "example.log",
  "size_in_bytes": 42,
  "created_at": "2021-03-23 16:41:50",
  "url": "xxx"
}
```
```suggestion
			fmt.Printf("\nCreateTarget() result:\n%s\n", string(b))
```

2021-03-24 21:10 UTC, padamstx approved these changes
LGTM

2021-03-25 09:47 UTC, pyrooka approved these changes
👍

2021-03-25 13:56 UTC, merged

2021-03-25 14:01 UTC, ibm-devx-automation commented
:tada: This PR is included in version 0.17.19 :tada:

The release is available on [GitHub release](https://github.com/IBM/platform-services-go-sdk/releases/tag/v0.17.19)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: